language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - php artisan migrate
  - php artisan db:seed --class=CodeceptSeed
  - php artisan db:seed --class=CodeceptSeedTwo

script:
  - composer install
  - php codecept run functional

after_success:
  - php coveralls

notifications:
  email: false
  slack:
    rooms:
      - ctlengineering:2jkLUalwb7dr9HJoLgsNlogf#builds
