language: php

php:
  - 7.0
  - hhvm

services:
  - mysql

before_script:
  - mv .env.example .env.testing
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  # For App
  - mysql -e 'create database laz'
  - chmod -R 777 storage/*
  - travis_retry php artisan migrate:install --env=testing --no-interaction -vvv


script:
  - composer install
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction --vvv --class=CodeceptSeed
  - php artisan db:seed --env=testing --no-interaction --vvv --class=CodeceptSeedTwo
  - php codecept run functional


after_success:
  - php coveralls

notifications:
  email: false
  slack:
    rooms:
      - ctlengineering:2jkLUalwb7dr9HJoLgsNlogf#builds
