language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - npm install
  - composer self-update

script:
  - gulp --production
  - composer install
  - phpunit --configuration phpunit.xml --coverage-text

after_success:
  - php vender/bin/coveralls -v


notifications:
  email: false
  slack:
    rooms:
      - ctlengineering:2jkLUalwb7dr9HJoLgsNlogf#builds

