language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

  matrix:
    exclude:
      - php: 7.0
        before_script: npm install

before_script:
  - composer self-update
  - npm install

script:
  - composer install
  - gulp --production
  - phpunit --configuration phpunit.xml --coverage-text

after_success:
  - php vender/bin/coveralls -v


notifications:
  email: false
  slack:
    rooms:
      - ctlengineering:2jkLUalwb7dr9HJoLgsNlogf#builds

