language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - phpenv config-rm ci-scripts/xdebug.sh
  - composer self-update
  - gulp --production

script:
  - composer install
  - npm install
  - phpunit --configuration phpunit.xml --coverage-text


notifications:
  email: false
  slack:
    rooms:
      - ctlengineering:2jkLUalwb7dr9HJoLgsNlogf#builds

